"""add_vacation_period

Revision ID: 1523323ae4ea
Revises: 337d58d04947
Create Date: 2026-08-15 08:18:10.836058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1523323ae4ea'
down_revision: Union[str, None] = '337d58d04947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacationperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planning_period_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['planning_period_id'], ['planningperiod.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacationperiod_user_id'), 'vacationperiod', ['user_id'], unique=False)
    op.add_column('specialday', sa.Column('required_doctors', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialday', 'required_doctors')
    op.drop_index(op.f('ix_vacationperiod_user_id'), table_name='vacationperiod')
    op.drop_table('vacationperiod')
    # ### end Alembic commands ###
