"""add_is_substitute

Revision ID: 21ef37339335
Revises: 1523323ae4ea
Create Date: 2026-08-15 08:39:48.205346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ef37339335'
down_revision: Union[str, None] = '1523323ae4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shiftassignment', sa.Column('is_substitute', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shiftassignment', 'is_substitute')
    # ### end Alembic commands ###
